import { useState } from "react";
import PageHeader from "./PageHeader";

export default function Documents({ documents, add, update, remove }) {
  const [name,setName]=useState(""); const [priority,setPriority]=useState("needed"); const [filter,setFilter]=useState("all"); const [editing,setEditing]=useState(null);
  const visible=documents.filter(x=>filter==="all"||x.priority===filter||filter==="copy"&&!x.copy||filter==="original"&&!x.original);
  function submit(e){e.preventDefault();if(!name.trim())return;editing?update("documents",editing,{name:name.trim(),priority}):add("documents",{name:name.trim(),priority,original:false,copy:false,description:""});setName("");setEditing(null)}
  return <><PageHeader title="مدارک" text="چک‌لیست مدارک خودت را بساز و وضعیت اصل و کپی را مشخص کن."/><form className="form-card inline-form" onSubmit={submit}><input value={name} onChange={e=>setName(e.target.value)} placeholder="نام مدرک"/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="required">واجب</option><option value="needed">مورد نیاز</option></select><button className="primary">{editing?"ذخیره":"افزودن"}</button></form><div className="filters">{[["all","همه"],["required","واجب"],["needed","مورد نیاز"],["original","اصل باقی‌مانده"],["copy","کپی باقی‌مانده"]].map(([id,l])=><button className={filter===id?"selected":""} key={id} onClick={()=>setFilter(id)}>{l}</button>)}</div><div className="list">{visible.length?visible.map(x=><article className="item" key={x.id}><div className="item-main"><strong>{x.name}</strong><div className="tags"><span>{x.priority==="required"?"واجب":"مورد نیاز"}</span></div><div className="checks"><label><input type="checkbox" checked={x.original} onChange={e=>update("documents",x.id,{original:e.target.checked})}/> اصل</label><label><input type="checkbox" checked={x.copy} onChange={e=>update("documents",x.id,{copy:e.target.checked})}/> کپی</label></div></div><div className="actions"><button onClick={()=>{setEditing(x.id);setName(x.name);setPriority(x.priority)}}>ویرایش</button><button onClick={()=>remove("documents",x.id)}>حذف</button></div></article>):<div className="empty">مدرکی ثبت نشده.</div>}</div></>;
}
