import { useState } from "react";
import PageHeader from "./PageHeader";

export default function Packing({ packing, add, update, remove }) {
  const [name,setName]=useState(""); const [priority,setPriority]=useState("needed"); const [qty,setQty]=useState(1); const [filter,setFilter]=useState("all"); const [editing,setEditing]=useState(null);
  const visible=packing.filter(x=>filter==="all"||x.priority===filter||filter=== (x.packed?"packed":"open"));
  function submit(e){e.preventDefault();if(!name.trim())return;const item={name:name.trim(),priority,qty:Number(qty)||1,packed:false,description:""};editing?update("packing",editing,item):add("packing",item);setName("");setQty(1);setEditing(null)}
  return <><PageHeader title="وسایل" text="چیزهایی که باید همراهت باشند."/><form className="form-card inline-form"><input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً داروهای شخصی"/><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="required">واجب</option><option value="needed">مورد نیاز</option></select><input className="qty" type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)}/><button className="primary" onClick={submit}>{editing?"ذخیره":"افزودن"}</button></form><div className="filters">{[["all","همه"],["required","واجب"],["needed","مورد نیاز"],["open","باقی‌مانده"],["packed","بسته‌شده"]].map(([id,l])=><button className={filter===id?"selected":""} key={id} onClick={()=>setFilter(id)}>{l}</button>)}</div><div className="list">{visible.length?visible.map(x=><article className={`item ${x.packed?"done":""}`} key={x.id}><input type="checkbox" checked={x.packed} onChange={e=>update("packing",x.id,{packed:e.target.checked})}/><div className="item-main"><strong>{x.name}</strong><div className="tags"><span>{x.priority==="required"?"واجب":"مورد نیاز"}</span><span>تعداد: {x.qty}</span></div></div><div className="actions"><button onClick={()=>{setEditing(x.id);setName(x.name);setPriority(x.priority);setQty(x.qty)}}>ویرایش</button><button onClick={()=>remove("packing",x.id)}>حذف</button></div></article>):<div className="empty">وسیله‌ای ثبت نشده.</div>}</div></>;
}
